config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # resources :reminders
  root 'reminders#new'
  post 'reminders', to: 'reminders#create'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/reminder.rb
class Reminder < ApplicationRecord
  before_create :create_reminder_time

  validates :name, presence: true
  validates :phone_number, presence: true, length: { in: 10..11 }, numericality: { only_integer: true }

 def create_reminder_time
   # create a reminder time
   ## Check for last reminder by the same creator
   past_reminder = Reminder.where(phone_number: self.phone_number)

   if (past_reminder.empty?)
     ## If empty response create a reminder
     today = Date.today()
     if today.monday?
       self.next_reminder = today.next_day(6)
     else
       self.next_reminder = today.next_day(8 - today.wday)
     end
   else
     ## Else use old date to and create a reminder for the net available monday
     self.next_reminder = next_available_monday(past_reminder.last.next_reminder)
   end


   # Put into a Task for Heroku to run
   # Check each user if they a reminder that needs to go
   # send the reminder

   # Put into a Task for Heroku to run
   #
 end
  private

  def next_available_monday(last_scheduled_day)
    last_scheduled_day.next_day.next_day(6)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/public_controller.rb
class PublicController < ApplicationController
  def index
  end
end

app/controllers/reminders_controller.rb
class RemindersController < ApplicationController
  before_action :set_reminder, only: [:show, :edit, :update, :destroy]

  # # GET /reminders
  # # GET /reminders.json
  # def index
  #   @reminders = Reminder.all
  # end
  #
  # # GET /reminders/1
  # # GET /reminders/1.json
  # def show
  # end

  # GET /reminders/new
  def new
    @reminder = Reminder.new
  end

  # GET /reminders/1/edit
  # def edit
  # end

  # POST /reminders
  # POST /reminders.json
  def create
    @reminder = Reminder.new(reminder_params)

    respond_to do |format|
      if @reminder.save
        format.html { redirect_to root_path, notice: 'Reminder was successfully created.' }
        format.json { render :show, status: :created, location: @reminder }
      else
        format.html { render :new }
        format.json { render json: @reminder.errors, status: :unprocessable_entity }
      end
    end
  end

  # # PATCH/PUT /reminders/1
  # # PATCH/PUT /reminders/1.json
  # def update
  #   respond_to do |format|
  #     if @reminder.update(reminder_params)
  #       format.html { redirect_to @reminder, notice: 'Reminder was successfully updated.' }
  #       format.json { render :show, status: :ok, location: @reminder }
  #     else
  #       format.html { render :edit }
  #       format.json { render json: @reminder.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end
  #
  # # DELETE /reminders/1
  # # DELETE /reminders/1.json
  # def destroy
  #   @reminder.destroy
  #   respond_to do |format|
  #     format.html { redirect_to reminders_url, notice: 'Reminder was successfully destroyed.' }
  #     format.json { head :no_content }
  #   end
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reminder
      @reminder = Reminder.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reminder_params
      params.require(:reminder).permit(:name, :phone_number, :notes)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/public_helper.rb
module PublicHelper
end

app/helpers/reminders_helper.rb
module RemindersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FindTime</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%# stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
      <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
      <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    </head>
    <body>
      <% flash.each do |type, msg| %>
        <div class="alert alert-info">
          <%= msg %>
        </div>
      <% end %>
      <%= yield %>
    </body>
  </html>

app/views/reminders/_form.html.erb
<%= form_with(model: reminder, local: true) do |form| %>
  <% if reminder.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(reminder.errors.count, "error") %> prohibited this reminder from being saved:</h2>

      <ul>
        <% reminder.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :phone_number %>
    <%= form.text_field :phone_number %>
  </div>

  <div class="field">
    <%= form.label :notes %>
    <%= form.text_area :notes %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/reminders/edit.html.erb
<h1>Editing Reminder</h1>

<%= render 'form', reminder: @reminder %>

<%= link_to 'Show', @reminder %> |
<%= link_to 'Back', reminders_path %>

app/views/reminders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reminders</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Phone number</th>
      <th>Notes</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reminders.each do |reminder| %>
      <tr>
        <td><%= reminder.name %></td>
        <td><%= reminder.phone_number %></td>
        <td><%= reminder.notes %></td>
        <td><%= link_to 'Show', reminder %></td>
        <td><%= link_to 'Edit', edit_reminder_path(reminder) %></td>
        <td><%= link_to 'Destroy', reminder, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reminder', new_reminder_path %>

app/views/reminders/new.html.erb
<h1>Find Time</h1>

<%= render 'form', reminder: @reminder %>

<%= link_to 'Back', reminders_path %>

app/views/reminders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @reminder.name %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @reminder.phone_number %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @reminder.notes %>
</p>

<%= link_to 'Edit', edit_reminder_path(@reminder) %> |
<%= link_to 'Back', reminders_path %>